### ISSUE TITLE
Using ImageNet pretrained weights?

### ISSUE THREAD

**Issue by TianheWu** [karttikeya/minREV#10]
Hi, thanks a lot for clean the complex code!
I want to know whether this clean code can load the ImageNet pretained weights and How?

**Comment by karttikeya** [comment]
Hi, 

This version of the reversible code cannot load in ImageNet weights natively. To do so you would have to make several changes to the model configurations. 

Instead, I would recommend you use the [rev code](https://github.com/facebookresearch/SlowFast/blob/main/slowfast/models/reversible_mvit.py) in pyslowfast. See readme for more details.
