### ISSUE TITLE
A model question

### ISSUE THREAD

**Issue by LKAMING97** [karttikeya/minREV#3]
Hello, I am a beginner and I find the code you provided concise and clear, making it easy to understand. However, I would like to use the "Stage-Transition Rev-MViT Block" from a research paper and I couldn't find it in SlowFast. Do you have any concise code that is similar to it?

**Comment by karttikeya** [comment]
Hi, 

Thanks for interest in our work. This repo has a minimalist implementation of Rev-ViT only. For Rev-MViT (that uses the  "Stage-Transition Rev-MViT Block" for paper) please see the full code in [reversible pyslowfast](https://github.com/facebookresearch/SlowFast/blob/main/slowfast/models/reversible_mvit.py).
