### ISSUE TITLE
Questions about MHA

### ISSUE THREAD

**Issue by kuviki** [karttikeya/minREV#4]
When I was learning the MHA implementation, I found that according to Pytorch's documentation: 
https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html
The default of batch_first parameter is False, then the shape of query, key, value should be (L,N,E)
https://github.com/karttikeya/minREV/blob/bf2b75dc69b573bdc3ab56dcf45a4a44ac337917/rev.py#L369
here the shape of tensor x is (N,L,E), is this a wrong writing?

**Comment by karttikeya** [comment]
good catch! fixed.
