### ISSUE TITLE
Mixed precision and Distributed training?

### ISSUE THREAD

**Issue by Maybe2022** [karttikeya/minREV#5]
Thank you for your great work. I want to try to use Mixed precision and Distributed to train the reversible architecture, but it cannot run your model successfully. I want to ask if the question appears？

**Comment by karttikeya** [comment]
Thanks for interest in our work! 

 I just added AMP to the training logic, it works fine. Please reference the implementation to cross-check differences. 

For DDP, all original results are trained with DDP which works the same with rev as vanilla. Please see readme for further info.
