### ISSUE TITLE
Using reversibility in language models?

### ISSUE THREAD

**Issue by vedantroy** [karttikeya/minREV#6]
While the paper on reversible transformers is about applications to vision, I have been training a multi-model that uses a reversible text transformer.

Is there any reason not to use reversibility in language transformers?

**Comment by karttikeya** [comment]
Hi @vedantroy,

Thanks for your interest in our work. There's no issues in using reversibility for LLMs. It has also been successfully applied to NLP tasks, however our work focuses on vision.
